{% set name = "kedro-aim" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kedro_aim-{{ version }}.tar.gz
  sha256: 306d5ab2e7196e808acdc4697f9a42fce84f622b2dc996854a53883b295298b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<3.11
    - kedro >=0.18.0
    - aim >=3.14.1,<4.0.0
    - pydantic >=1.10.2,<2.0.0

test:
  imports:
    - kedro_aim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://kedro-aim.readthedocs.io
  summary: A plugin to integrate the mlops plattform aim into your kedro project
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
